FROM debian9

MAINTAINER 坚硬的石头 do_nb@outlook.com

RUN apt-get update && apt-get install redis-server redis-tools -y && \
        rm -rf /var/lib/apt/lists/*

#EXPOSE 6379

CMD ["/usr/bin/redis-server"]

